MidiEncoder:
  number_timeslices: 64
  number_instruments: 9
  midi_embedding_dim: 9
  dropout: 0.1
  transformer_ff_dim: 512
  num_heads: 3

TextEncoder:
  bert_embedding_dim: 512
  dropout: 0.1


ProjectionHead:
  projection_dim: 32
  dropout: 0.1

CLAMP:
  number_timeslices: 100
  number_instruments: 10

Training:
  batch_size: 32
  learning_rate: 0.001
  optimizer: 'adam'
  epochs: 100
  gradient_clip: 5.0
  weight_decay: 0.0005
  learning_rate_decay: 0.95
  patience: 3
  device: 'cuda'
  checkpoint_interval: 5
  validate_interval: 1
  log_interval: 100
  dataset_path: './data/dataset/'
  pretrained_model_path: None
  save_model_path: './trained_models/'
  load_from_checkpoint: False
  checkpoint_path: './checkpoint/'
  temperature: 0.07

